    spring.application.name=restoradar

# Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.idpagpzstxjeimimgixk
spring.datasource.password=1-iNAX3QJLDE
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=y#p)$y=k4gw&oet-*&f+xbtljghuwvm6-mpm6f@jr_v%2a0e2a
jwt.expiration=900000
jwt.refresh.expiration=604800000

spring.security.oauth2.client.registration.google.client-id=351738559457-3gh3eje3n7he1mq3nu243a3k72li4nbv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
app.frontend.url=http://localhost:5173